version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Jakarta"

    open-pull-requests-limit: 10
    versioning-strategy: increase

    ignore:
      - dependency-name: "@saleshub-tsm/types"

    groups:
      nextjs:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@types/react*"

      prisma:
        patterns:
          - "@prisma/*"
          - "prisma"

      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "@typescript-eslint/*"

      radix:
        patterns:
          - "@radix-ui/*"

      fontawesome:
        patterns:
          - "@fortawesome/*"

  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Jakarta"

    open-pull-requests-limit: 5

    ignore:
      - dependency-name: "@saleshub-tsm/types"

  - package-ecosystem: "npm"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Jakarta"

    open-pull-requests-limit: 5

    ignore:
      - dependency-name: "@saleshub-tsm/types"